language: julia
sudo: false

before_install:
    - git submodule update --init

install: travis_wait mvn install

os:
    - linux
    - osx

julia:
    - 0.5

script:
    - sh tests/run_travis_tests.sh